export const ACTIONS_GET_BANNER = 'ACTIONS_GET_BANNER'
export const MUTATIONS_GET_BANNER = 'MUTATIONS_GET_BANNER'
export const ACTIONS_GET_PLAYLIST = 'ACTIONS_GET_PLAYLIST'
export const MUTATIONS_GET_PLAYLIST = 'MUTATIONS_GET_PLAYLIST'
