// banner
export const ACTIONS_GET_BANNER = 'ACTIONS_GET_BANNER'
export const MUTATIONS_GET_BANNER = 'MUTATIONS_GET_BANNER'
// 推荐歌单
export const ACTIONS_GET_PLAYLIST = 'ACTIONS_GET_PLAYLIST'
export const MUTATIONS_GET_PLAYLIST = 'MUTATIONS_GET_PLAYLIST'
// 最新音乐
export const ACTIONS_GET_NEWSONG = 'ACTIONS_GET_NEWSONG'
export const MUTATIONS_GET_NEWSONG = 'MUTATIONS_GET_NEWSONG'
// 推荐mv
export const ACTIONS_GET_MV = 'ACTIONS_GET_MV'
export const MUTATIONS_GET_MV = 'MUTATIONS_GET_MV'
// 歌手列表
export const GETTERS_GET_SINGER_PARAM = 'GETTERS_GET_SINGER_PARAM'
export const MUTATIONS_SET_SINGER_INIT = 'MUTATIONS_SET_SINGER_INIT'
export const ACTIONS_GET_SINGER_LIST = 'ACTIONS_GET_SINGER_LIST'
export const MUTATIONS_GET_SINGER_LIST = 'MUTATIONS_GET_SINGER_LIST'
export const MUTATIONS_SET_SINGER_LOAD = 'MUTATIONS_SET_SINGER_LOAD'
export const MUTATIONS_CHANGE_SINGER_LIST = 'MUTATIONS_CHANGE_SINGER_LIST'
export const MUTATIONS_CHANGE_SINGER_PAGE = 'MUTATIONS_CHANGE_SINGER_PAGE'
// 歌单列表
export const GETTERS_GET_PLAYLIST_PARAM = 'GETTERS_GET_PLAYLIST_PARAM'
export const MUTATIONS_SET_PLAYLIST_INIT = 'MUTATIONS_SET_PLAYLIST_INIT'
export const ACTIONS_GET_PLAYLIST_CATEGORY = 'ACTIONS_GET_PLAYLIST_CATEGORY'
export const MUTATIONS_GET_PLAYLIST_CATEGORY_HOT = 'MUTATIONS_GET_PLAYLIST_CATEGORY_HOT'
export const MUTATIONS_GET_PLAYLIST_CATEGORY_ALL = 'MUTATIONS_GET_PLAYLIST_CATEGORY_ALL'
export const ACTIONS_GET_PLAY_LIST = 'ACTIONS_GET_PLAY_LIST'
export const MUTATIONS_GET_PLAY_LIST = 'MUTATIONS_GET_PLAY_LIST'
export const MUTATIONS_CHANGE_PALYLIST_TITLE = 'MUTATIONS_CHANGE_PALYLIST_TITLE'
export const MUTATIONS_CHANGE_PALYLIST_TAG = 'MUTATIONS_CHANGE_PALYLIST_TAG'
export const MUTATIONS_SET_PLAYLIST_LOAD = 'MUTATIONS_SET_PLAYLIST_LOAD'
export const MUTATIONS_CHANGE_PLAYLIST_PAGE = 'MUTATIONS_CHANGE_PLAYLIST_PAGE'
// 搜索
export const MUTATIONS_GET_SEARCH_KEY = 'MUTATIONS_GET_SEARCH_KEY'
export const MUTATIONS_GET_SEARCH_HOT = 'MUTATIONS_GET_SEARCH_HOT'
export const MUTATIONS_GET_SEARCH_LIST = 'MUTATIONS_GET_SEARCH_LIST'
export const ACTIONS_GET_SEARCH_DEFAULT = 'ACTIONS_GET_SEARCH_DEFAULT'
export const ACTIONS_GET_SEARCH_LIST = 'ACTIONS_GET_SEARCH_LIST'
export const MUTATIONS_GET_SEARCH_SUGGEST = 'MUTATIONS_GET_SEARCH_SUGGEST'
